version: '2'
services:
  envoy:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    command: /usr/local/bin/envoy -c /etc/envoy.yaml
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
      - ./runtime:/srv/runtime
    networks:
      - envoymesh
    ports:
      - 9211:9211
      - 9901:9901
  backend:
    image: kennethreitz/httpbin@sha256:599fe5e5073102dbb0ee3dbb65f049dab44fa9fc251f6835c9990f8fb196a72b
    networks:
      - envoymesh
    ports:
      - 8080:80
networks:
  envoymesh: {}
